---
title: "working on cbf data"
output:
  html_notebook: default
  pdf_document: default
---


```{r}
test_set <- read.table("~/Desktop/NCSA/cbf/CBF_TEST.txt", header=F, sep = "")
full_set <- read.table("~/Desktop/NCSA/cbf/CBF_TRAIN.txt", header=F, sep = "")
#training_set <- full_set[sample(1:nrow(full_set), replace = TRUE),]

training_frame = as.data.frame(full_set)
training_frame

s = test_set[sample(1:nrow(test_set), replace = TRUE),]
test_frame = as.data.frame(s[1:10,])
test_frame
```

```{r}
print("Training set has 900 TS models with 130 datapoints each")
xrange <- range(0:130)
yrange <- range(-2:3)

plot(xrange,yrange,type='n', xlab='time',ylab='values')
lines(unlist(list(training_frame[1,])), type = 'l', col='red')
lines(unlist(list(training_frame[2,])), type = 'l', col='green')
lines(unlist(list(training_frame[3,])), type = 'l', col='yellow')
lines(unlist(list(training_frame[4,])), type = 'l', col='blue')
lines(unlist(list(training_frame[5,])), type = 'l', col='orange')

```

```{r}
print("Test set has 30 TS models with 130 datapoints each")
xrange <- range(0:130)
yrange <- range(-2:3)

plot(xrange,yrange,type='n', xlab='time',ylab='values')
lines(unlist(list(test_frame[1,])), type = 'l', col='red')
lines(unlist(list(test_frame[2,])), type = 'l', col='green')
lines(unlist(list(test_frame[3,])), type = 'l', col='yellow')
lines(unlist(list(test_frame[4,])), type = 'l', col='blue')
lines(unlist(list(test_frame[5,])), type = 'l', col='orange')
```

```{r}
require(dtwclust)
```

```{r}
clust.hier <- tsclust(training_frame, type = "h", k = 3L, distance = "dtw2", trace=TRUE)

plot(clust.hier, type="sc")
```

```{r}
t(cbind(training_frame[,0], cluster = clust.hier@cluster))
```





```{r}
plot(xrange,yrange,type='n', xlab='time',ylab='values')
lines(unlist(list(test_frame[1,])), type = 'h', col='red')
predict(clust.hier,newdata=unlist(list(test_frame[1,])))
```

```{r}
plot(xrange,yrange,type='n', xlab='time',ylab='values')
lines(unlist(list(test_frame[2,])), type = 'h', col='red')
predict(clust.hier,newdata=unlist(list(test_frame[2,])))
```


```{r}
plot(xrange,yrange,type='n', xlab='time',ylab='values')
lines(unlist(list(test_frame[3,])), type = 'h', col='red')
predict(clust.hier,newdata=unlist(list(test_frame[3,])))
```

```{r}
plot(xrange,yrange,type='n', xlab='time',ylab='values')
lines(unlist(list(test_frame[4,])), type = 'h', col='red')
predict(clust.hier,newdata=unlist(list(test_frame[4,])))
```

```{r}
plot(xrange,yrange,type='n', xlab='time',ylab='values')
lines(unlist(list(training_frame[5,])), type = 'h', col='red')
predict(clust.hier,newdata=unlist(list(training_frame[5,])))
```