---
title: "R Notebook"
output: html_notebook
---

```{r}
require(forecast)
```

```{r}
series = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID01.csv')
series$glucoseValue[series$glucoseValue==0.0] <- NA
```

```{r}
series = na.omit(series)
```


```{r}
plot(series$glucoseValue, type='l')
```

```{r}
series_new = series
```


```{r}
locs = sample(1:nrow(series), 1000, replace = FALSE)
locs
```

```{r}
for (i in 1:1000) {
  l = locs[i]
  series_new$glucoseValue[l] = NA
}
```


```{r}
plot(series_new$glucoseValue, type='l')
```



```{r}
series_new$glucoseValue = na.interp(series_new$glucoseValue)
```

```{r}
plot(series_new$glucoseValue, type='l')
```



```{r}
rss = 0
for (i in 1:nrow(series)) {
  rss = rss + (series$glucoseValue[i]-series_new$glucoseValue[i]) ^ 2
}
rss
rse = (rss/(nrow(series)-2)) ^ 0.5
rse
```


```{r}
require(openair)
```


```{r}
x = data.frame("real" = series$glucoseValue, 'imputed' = series_new$glucoseValue)
temp4 = modStats(x,mod = "imputed",obs = "real", statistic = c("IOA"))
typeof(temp4$IOA)
```

