---
title: "R Notebook"
output: html_notebook
---

```{r}
require(zoo)
```

```{r}
series = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID01.csv')
series$glucoseValue[series$glucoseValue==0.0] <- NA
```

```{r}
series = na.omit(series)
```


```{r}
plot(series$glucoseValue, type='l')
```

```{r}
series_new = series

locs = sample(2:nrow(series), 1000, replace = FALSE)

for (i in 1:1000) {
  l = locs[i]
  series_new$glucoseValue[l] = NA
}

plot(series_new$glucoseValue, type='l')
```


```{r}
aggr = na.aggregate(series_new$glucoseValue)
#aggr

```

```{r}
rss = 0
for (i in 1:nrow(series)) {
  rss = rss + (series$glucoseValue[i]-aggr[i]) ^ 2
}
rss
rse = (rss/(nrow(series)-2)) ^ 0.5
rse
```

```{r}
approx = na.approx(series_new$glucoseValue)
plot(approx, type='l')
```

```{r}
rss_approx = 0
for (i in 1:length(approx)) {
  rss_approx = rss_approx + (series$glucoseValue[i]-approx[i]) ^ 2
  #print(rss_approx)
}
rss_approx
rse_approx = (rss_approx/(nrow(series)-2)) ^ 0.5
rse_approx
```

```{r}
locf = na.locf(series_new$glucoseValue)
plot(locf,type='l')
```

```{r}
rss_locf = 0
for (i in 1:length(locf)) {
  rss_locf = rss_locf + (series$glucoseValue[i]-locf[i]) ^ 2
  #print(rss_approx)
}
rss_locf
rse_locf = (rss_locf/(nrow(series)-2)) ^ 0.5
rse_locf
```

```{r}
spline = na.spline(series_new$glucoseValue)
plot(spline,type='l')
```

```{r}
rss_spline = 0
for (i in 1:length(spline)) {
  rss_spline = rss_spline + (series$glucoseValue[i]-spline[i]) ^ 2
  #print(rss_approx)
}
rss_spline
rse_spline = (rss_spline/(nrow(series)-2)) ^ 0.5
rse_spline
```




```{r}

x = as.ts(series_new)
x
s = na.StructTS(x)
s
#struct = na.StructTS(series_new$glucoseValue)
#plot(struct,type='l')
```

```{r}
rss_struct = 0
for (i in 1:length(struct)) {
  rss_struct = rss_struct + (series$glucoseValue[i]-struct[i]) ^ 2
  #print(rss_approx)
}
rss_struct
rse_struct = (rss_struct/(nrow(series)-2)) ^ 0.5
rse_struct
```