---
title: "R Notebook"
output: html_notebook
---

```{r}
m1 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID01.csv')
m2 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID02.csv')
m3 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID03.csv')
m4 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID11.csv')
m5 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID12.csv')
m6 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID13.csv')
m7 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID21.csv')
m8 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID22.csv')
m9 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID23.csv')
m10 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID29.csv')
m11 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID30.csv')
m12 = read.csv('~/Desktop/NCSA/CGManalyzer-datasets/ID31.csv')

training_frame = rbind.data.frame(
                            m1$glucoseValue,
                            m2$glucoseValue,
                            m3$glucoseValue,
                            m4$glucoseValue,
                            m5$glucoseValue,
                            m6$glucoseValue,
                            m7$glucoseValue,
                            m8$glucoseValue,
                            m9$glucoseValue,
                            m10$glucoseValue,
                            m11$glucoseValue,
                            m12$glucoseValue
                            )
training_frame
```

```{r}
Acluster <- kmeans(training_frame, 4)
#Acluster
```



```{r}
l=Acluster$cluster
l
```

```{r}
m = c(2,2,2,3,3,3,4,4,4,1,1,1)
require(mcclust)
arandi(l,m)
arandi(l,m,adjust=FALSE)

```


