---
title: "Simple DTW"
output: html_notebook
---

```{r}
data1 <- c(7,9,6,9,2,6,4,6,8)
data2 <- c(5,6,4,3,9,5,6,8,9)
cols <- c(1,2,3,4,5,6,7,8,9)


xrange <- range(1:9)
yrange <- range(min(c(data1,data2)), max(data1,data2))

plot(xrange,yrange,type='n', xlab='time',ylab='values')
lines(data1, type = 'l', col='red')
lines(data2, type = 'l', col='green')

```

```{r}
#install.packages("dtw")
```

```{r}
require(dtw)
```

```{r}
dtw(data1,data2)$index1
```


```{r}
dtw(data1,data2)$index2
```

```{r}
plot(dtw(data1,data2), xlab="data1", ylab="data2", xaxp  = c(0,10,10), yaxp = c(0,10,10))
```

```{r}
plot(dtw(data1,data2, keep=TRUE), xlab="data1", ylab="data2", xaxp  = c(0,10,10), yaxp = c(0,10,10), type="threeway")
```


```{r}
plot(dtw(data1,data2, keep=TRUE), xaxp  = c(0,10,10), yaxp = c(0,10,10), type="twoway", col=c('red', 'green'))
```




```{r}
data3 <- c(2,6,9,1,3,5,1,7,1)
data4 <- c(3,8,1,2,6,4,2,9,5)
data5 <- c(7,6,2,1,5,2,7,4,9)
data6 <- c(7,5,1,4,6,1,8,5,8)
frame<-rbind(data1,data2,data3,data4,data5)
frame

xrange <- range(1:9)
yrange <- range(min(c(data1,data2,data3,data4,data5)), max(data1,data2,data3,data4,data5))
plot(xrange,yrange,type='n', xlab='time',ylab='values')
lines(data1, type = 'l', col='red')
lines(data2, type = 'l', col='green')
lines(data3, type = 'l', col='yellow')
lines(data4, type = 'l', col='blue')
lines(data5, type = 'l', col='cyan')
lines(data6, type = 'l', col='orange')
```

```{r}
#install.packages("dtwclust")
```

```{r}
require(dtwclust)
```

```{r}
clust.pam <- tsclust(frame, type="partitional", k=3L, distance="dtw2", clustering="pam")
plot(clust.pam, type = "sc")
```
The dashed line represents the medoid time series.


```{r}
t(cbind(frame[,0], cluster = clust.pam@cluster))
```
```{r}
predict(clust.pam,newdata=data6)
```



```{r}
clust.hier <- tsclust(frame, type = "h", k = 3L, distance = "dtw2", trace=TRUE)
plot(clust.hier)

plot(clust.hier, type="sc")
```

```{r}
t(cbind(frame[,0], cluster = clust.hier@cluster))
```


```{r}
predict(clust.hier,newdata=data6)
```


============== Linear Scaling ===============
```{r}
linearScaling = function(data){
  scaled = c()
  for (i in 1:length(data)) {
    scaled[i] = (data[i]-min(data))/(max(data)-min(data))
    #print(scaled[i])
  }
  return(scaled)
}


linear_data_1 = linearScaling(data1)
linear_data_2 = linearScaling(data2)
linear_data_3 = linearScaling(data3)
linear_data_4 = linearScaling(data4)
linear_data_5 = linearScaling(data5)
linear_data_6 = linearScaling(data6)


frame_linear<-rbind(linear_data_1,linear_data_2,linear_data_3,linear_data_4,linear_data_5)
frame_linear

xrange <- range(1:9)
yrange <- range(0:1)
plot(xrange,yrange,type='n', xlab='time',ylab='values')
lines(linear_data_1, type = 'l', col='red')
lines(linear_data_2, type = 'l', col='green')
lines(linear_data_3, type = 'l', col='yellow')
lines(linear_data_4, type = 'l', col='blue')
lines(linear_data_5, type = 'l', col='cyan')

```


```{r}
clust.hier_linear <- tsclust(frame_linear, type = "h", k = 3L, distance = "dtw2", trace=TRUE)
plot(clust.hier_linear)

plot(clust.hier_linear, type="sc")
```

```{r}
t(cbind(frame_linear[,0], cluster = clust.hier_linear@cluster))
```


```{r}
predict(clust.hier_linear,newdata=linear_data_6)
```




============== Log Scaling ===============
```{r}
logScaling = function(data){
  scaled = c()
  for (i in 1:length(data)) {
    scaled[i] = log(data[i])
    #print(scaled[i])
  }
  return(scaled)
}


log_data_1 = logScaling(data1)
log_data_2 = logScaling(data2)
log_data_3 = logScaling(data3)
log_data_4 = logScaling(data4)
log_data_5 = logScaling(data5)
log_data_6 = logScaling(data6)


frame_log<-rbind(log_data_1,log_data_2,log_data_3,log_data_4,log_data_5)
frame_log

xrange <- range(1:9)
yrange <- range(0:3)
plot(xrange,yrange,type='n', xlab='time',ylab='values')
lines(log_data_1, type = 'l', col='red')
lines(log_data_2, type = 'l', col='green')
lines(log_data_3, type = 'l', col='yellow')
lines(log_data_4, type = 'l', col='blue')
lines(log_data_5, type = 'l', col='cyan')


```


```{r}
clust.hier_log <- tsclust(frame_log, type = "h", k = 3L, distance = "dtw2", trace=TRUE)
plot(clust.hier_log)

plot(clust.hier_log, type="sc")
```

```{r}
t(cbind(frame_log[,0], cluster = clust.hier_log@cluster))
```


```{r}
predict(clust.hier_log,newdata=log_data_6)
```

