---
title: "Spectral for time series"
output: html_notebook
---

```{r}
data = read.csv("~/Desktop/NCSA/CGManalyzer-datasets/ID11.csv")
data <- data[data$glucoseValue!=0,]
data
```


```{r}
plot(data$timeStamp, data$glucoseValue, type='b')
```

```{r}
x = data['glucoseValue']
#x

standardize<-function(x){
  for(i in 1:dim(x)[2]){x[,i] = (x[,i] -mean(x[,i]))/sd(x[,i])}
  return(x)
}
X<-as.data.frame(standardize(x))
boxplot(X)
X
```

```{r}
model <- kmeans(X,3)
summary(model)
table(model$cluster,as.numeric(data[,2]))
```


```{r}
#Spectral Clustering
nodes <- dim(X)[1]
S <- matrix(NA,nrow=nodes,ncol=nodes) #similarity matrix
sigma <- 1
for(i in 1:nodes){
  for(j in 1:nodes){
    S[i,j] <- exp(-sum((X[i,] - X[j,])^2)/(2*sigma^2)) #fully connected graph => gaussian similarity function
  }
}

S_degree <- rowSums(S)
Laplacian <- diag(S_degree) - S
normalized_Laplacian <- diag(S_degree^(-1/2)) %*% S #random walk laplacian
```

```{r}
# error = sum(S[i,j] * (fi - fj)^2)
ev <- eigen(Laplacian)
e <- kmeans(ev$vectors[,which.min(ev$values)],3)$cluster
table(e,as.numeric(data[,2]))
```




```{r}
ev <- eigen(normalized_Laplacian)
ev_vector <- ev$vectors[,1:3]
for(i in 1:nodes){
  ev_vector[i,] <- ev_vector[i,] / sqrt(sum(ev_vector[i,]^2))
}
e <- kmeans(ev_vector,3)$cluster
table(e,as.numeric(data[,2]))
```
