---
title: "DTW CLUSTERING ON TIME SERIES"
output: html_notebook
---

```{r}
sc <- read.csv('~/Desktop/NCSA/dataset.csv', header=F)
sc

```

```{r}
n<-10
s <- sample(1:100, n)
s
idx <- c(s, 100+s, 200+s, 300+s, 400+s, 500+s)
idx
sample2 <- sc[idx,]
sample2

```

```{r}
observedLabels <- c(rep(1,n), rep(2,n), rep(3,n), rep(4,n), rep(5,n), rep(6,n))

# compute DTW distances

library(dtw)

distMatrix <- dist(sample2, method="DTW")

# hierarchical clustering

hc <- hclust(distMatrix, method="average")

plot(hc, labels=observedLabels, main=" ")
```

```{r}
sc <- read.table("~/Desktop/NCSA/dataset.csv", header=F, sep = ",")
sc
# randomly sampled n cases from each class, to make it easy for plotting

n <- 100

s <- sample(1:100, n)

idx <- c(s, 100+s, 200+s, 300+s, 400+s, 500+s)

sample2 <- sc[idx,]
sample2
typeof(sample2)

observedLabels <- c(rep(1,n), rep(2,n), rep(3,n), rep(4,n), rep(5,n), rep(6,n))

# compute DTW distances
x = as.numeric(unlist(sample2))
#x
#typeof(x)
l = list(x)
l
#typeof(l)


library(dtw)

distMatrix <- dist(l, method="DTW")
distMatrix

# hierarchical clustering

#hc <- hclust(distMatrix)

#plot(hc, labels=observedLabels, main="")
```

